spring.application.name=backend
# === CONFIGURATION DE LA BASE DE DONNÉES POSTGRESQL ===
spring.datasource.url=jdbc:postgresql://localhost:5433/healthtrack_db
spring.datasource.username=postgres
spring.datasource.password=admin

# === CONFIGURATION HIBERNATE / JPA ===
# 'update' permet à Spring de créer ou modifier les tables automatiquement à chaque démarrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect